### ISSUE TITLE
demo-25-issue1

### ISSUE THREAD

**Issue by SapneshNaik** [SapneshNaik/GIT-CF-Demo#1]
## Emphasis

**This is bold text**

__This is bold text__

*This is italic text*

_This is italic text_

~~Strikethrough~~

## Blockquotes

> Blockquotes can also be nested...
>> ...by using additional greater-than signs right next to each other...
> > > ...or with spaces between arrows.

## Lists

Unordered

+ Create a list by starting a line with `+`, `-`, or `*`
+ Sub-lists are made by indenting 2 spaces:
  - Marker character change forces new list start:
    * Ac tristique libero volutpat at
    + Facilisis in pretium nisl aliquet
    - Nulla volutpat aliquam velit
+ Very easy!

Ordered

1. Lorem ipsum dolor sit amet
2. Consectetur adipiscing elit
3. Integer molestie lorem at massa

1. You can use sequential numbers...
1. ...or keep all the numbers as `1.`

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $55.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/demo-25-issue1).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $100.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/funder2">funder2</a>
Co-Funder Message: I would like to support this issue.

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> has been approved to start work.**

<hr />

**Message:** Go ahead


<a href='https://sandbox.app.gitcommits.com/issue/demo-25-issue1'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a>, Your submission has been rejected by <a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a>.**
<hr />

**Message:** Pull Request has been rejected.


<a href='https://sandbox.app.gitcommits.com/issue/demo-25-issue1'>Click Here to view more</a> on GitCommits Bounty detail page.
